# Generated by Django 5.2.5 on 2025-08-12 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_quiz_is_shared_quiz_share_code_quizshare_quizattempt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizshare',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='is_shared',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='share_code',
        ),
        migrations.DeleteModel(
            name='QuizAttempt',
        ),
        migrations.DeleteModel(
            name='QuizShare',
        ),
    ]
